# Base Python: Read and write files

### 1. Open a txt file named 'Hello world' and write all elements of the list x in newlines, then open that file and print all lines in the file

```python
x = ['Python is flexible','but', 'Python is slow!']
```

# Pandas is built on Numpy

In [ ]:
import pandas as pd

# test comment 1
# test comment 2

## Pandas can read:

1. CSV (Comma-Separated Values)
    - Function: pd.read_csv()
    - Description: CSV files are simple text files where data is separated by commas (or other delimiters).
    - Example: df = pd.read_csv('data.csv')
2. Excel Files (XLSX/XLS)
    - Function: pd.read_excel()
    - Description: Pandas can read from both .xlsx (Excel 2007+) and .xls (older Excel formats).
    - Example: df = pd.read_excel('data.xlsx', sheet_name='Sheet1')
3. JSON (JavaScript Object Notation)
    - Function: pd.read_json()
    - Description: JSON files can store structured data as key-value pairs, often used in web applications.
    - Example: df = pd.read_json('data.json')
4. SQL Databases
    - Function: pd.read_sql(), pd.read_sql_query(), pd.read_sql_table()
    - Description: Pandas can read data from SQL databases such as SQLite, PostgreSQL, MySQL, etc.
    - Example: Query: df = pd.read_sql_query('SELECT * FROM table_name', connection), Full Table: df = pd.read_sql_table('table_name', connection)
5. XML Files
    - Function: pd.read_xml()
    - Description: XML is a markup language commonly used for data exchange. Pandas can read XML and convert it into a DataFrame.
    - Example: df = pd.read_xml('data.xml')
6. Plain Text Files
    - Function: pd.read_fwf() (for fixed-width formatted files), pd.read_csv('',delimiter='') (for delimited text files)
    - Description: Text files with either fixed-width columns or custom delimiters.
    - Example: df = pd.read_fwf('data.txt')
7. Compressed Files
    - Function: pd.read_csv(), pd.read_json(), pd.read_parquet(), etc. (with compression specified)
    - Description: Pandas can automatically handle compressed files such as .gz, .bz2, .zip, .xz.
    - Example: df = pd.read_csv('data.csv.gz')
      
AND MUCH MORE...

In [ ]:
df = pd.read_csv('Health_Sleep_Statistics.csv')
df.tail(3)
df.head(4)

df.columns
df[['Age','User ID']].head(2) #[0:3]
df.iloc[0:4,1] # df.iloc[r,c]

df.loc[df['Gender']== 'f'].head(3)

df.loc[df['Bedtime']== '23:00']
df.describe().round()
df

,User ID,Age,Gender,Sleep Quality,Bedtime,Wake-up Time,Daily Steps,Calories Burned,Physical Activity Level,Dietary Habits,Sleep Disorders,Medication Usage
0,1,25,f,8,23:00,06:30,8000,2500,medium,healthy,no,no
1,2,34,m,7,00:30,07:00,5000,2200,low,unhealthy,yes,yes
2,3,29,f,9,22:45,06:45,9000,2700,high,healthy,no,no
3,4,41,m,5,01:00,06:30,4000,2100,low,unhealthy,yes,no
4,5,22,f,8,23:30,07:00,10000,2800,high,medium,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,43,m,7,00:45,07:15,6500,2400,medium,medium,no,no
96,97,33,f,8,23:15,06:15,8500,2600,high,medium,no,no
97,98,46,m,4,01:30,07:00,3000,2000,low,unhealthy,yes,yes
98,99,25,f,9,22:15,06:45,9500,2700,high,healthy,no,no
99,100,41,m,6,00:30,07:00,5000,2200,medium,unhealthy,no,no

## Exercises

### 1. Load the CSV file and display the first 10 rows of the dataset. Then, print the summary statistics of the Daily Steps and Calories Burned columns

In [81]:
import pandas as pd
df = pd.read_csv('Health_Sleep_Statistics.csv')
df.head(10)
df[['Daily Steps', 'Calories Burned']].describe().round(2)

       Daily Steps  Calories Burned
count       100.00           100.00
mean       6830.00          2421.00
std        2498.71           281.07
min        3000.00          2000.00
25%        4750.00          2175.00
50%        6750.00          2400.00
75%        9000.00          2700.00
max       11000.00          2900.00

In [7]:
f = pd.unique(df['Gender'])
print(f,type(f))

['f' 'm'] <class 'numpy.ndarray'>

### 2. Filter the dataset to find users who have a sleep quality score below 3 and burn more than 2500 calories per day. Display their User ID, Age, and Sleep Quality

In [ ]:
# noone with sleep quality below 3, was it meant above?
filtered_df = df[(df['Sleep Quality']>3) & (df['Calories Burned']>2500)]
filtered_df[['User ID','Age','Sleep Quality']]

    User ID  Age  Sleep Quality
2         3   29              9
4         5   22              8
6         7   30              8
8         9   27              9
11       12   23              9
14       15   28              9
18       19   33              9
20       21   29              8
22       23   40              9
24       25   32              8
26       27   27              9
30       31   24              9
32       33   37              8
34       35   28              9
38       39   26              9
40       41   30              8
42       43   34              9
46       47   28              9
48       49   32              8
50       51   23              9
52       53   27              8
54       55   29              9
56       57   30              8
58       59   25              9
60       61   28              8
62       63   26              9
64       65   31              8
66       67   24              9
68       69   28              8
70       71   32              9
72       73   29              8
74       75   26              9
76       77   30              8
78       79   25              9
80       81   31              8
82       83   27              9
84       85   34              8
86       87   28              9
88       89   30              8
90       91   23              9
92       93   29              8
94       95   27              9
96       97   33              8
98       99   25              9

### 3. Create a new column called Sleep Duration that calculates the duration of sleep in hours using the Bedtime and Wake-up Time columns. Assume these columns are in 24-hour format (e.g., "22:30", "06:45")

In [82]:
# Convert Bedtime and Wake-up Time to datetime objects (with seconds included)
df['Bedtime'] = pd.to_datetime(df['Bedtime'], format='%H:%M')
df['Wake-up Time'] = pd.to_datetime(df['Wake-up Time'], format='%H:%M')

# Subtract and calculate sleep duration in hours
df['Sleep Duration'] = (df['Wake-up Time'] - df['Bedtime']).dt.total_seconds() / 3600
df.loc[df['Sleep Duration'] <= 0, 'Sleep Duration'] = df['Sleep Duration'] + 24
# Handle cases where bedtime is after midnight
#df['Sleep Duration'] = df['Sleep Duration'].apply(lambda x: x if x > 0 else x + 24)

print(df.head(3))

   User ID  Age Gender  Sleep Quality             Bedtime        Wake-up Time  \
0        1   25      f              8 1900-01-01 23:00:00 1900-01-01 06:30:00
1        2   34      m              7 1900-01-01 00:30:00 1900-01-01 07:00:00
2        3   29      f              9 1900-01-01 22:45:00 1900-01-01 06:45:00

   Daily Steps  Calories Burned Physical Activity Level Dietary Habits  \
0         8000             2500                  medium        healthy
1         5000             2200                     low      unhealthy
2         9000             2700                    high        healthy

  Sleep Disorders Medication Usage  Sleep Duration
0              no               no             7.5
1             yes              yes             6.5
2              no               no             8.0

### 4. Find the user with the maximum physical activity level and display their User ID, Daily Steps, Calories Burned, and Physical Activity Level.

In [ ]:

# Find the row with the maximum calories burned
max_activity_user = df.loc[df['Calories Burned'].idxmax()]

# Display User ID, Daily Steps, Calories Burned, and Physical Activity Level
print(max_activity_user[['User ID', 'Daily Steps', 'Calories Burned', 'Physical Activity Level']])

User ID                       12
Daily Steps                11000
Calories Burned             2900
Physical Activity Level      NaN
Name: 11, dtype: object

### 5. Group the users by Gender and calculate the average Daily Steps and Calories Burned for each gender

In [11]:
# Group by Gender and calculate the mean of Daily Steps and Calories Burned
gender_group = df.groupby('Gender')[['Daily Steps', 'Calories Burned']].mean()

print(gender_group)

        Daily Steps  Calories Burned
Gender
f            8940.0           2654.0
m            4720.0           2188.0

### 6. Check if there are any missing values in the dataset and fill them with appropriate values. For numeric columns, fill with the column mean, and for categorical columns, fill with the mode

In [83]:
# Step 1: Check for missing values
print("Missing values before filling:")
print(df.isnull().sum())

# Step 2: Fill missing values
for column in df.columns:
    if df[column].dtype in ['float64', 'int64']:  # Numeric columns
        mean_value = df[column].mean()
        df[column].fillna(mean_value, inplace=True)
    else:  # Categorical columns (object, string, etc.)
        mode_value = df[column].mode()[0]
        df[column].fillna(mode_value, inplace=True)

# Step 3: Verify
print("\nMissing values after filling:")
print(df.isnull().sum())

Missing values before filling:
User ID                    0
Age                        0
Gender                     0
Sleep Quality              0
Bedtime                    0
Wake-up Time               0
Daily Steps                0
Calories Burned            0
Physical Activity Level    0
Dietary Habits             0
Sleep Disorders            0
Medication Usage           0
Sleep Duration             0
dtype: int64

Missing values after filling:
User ID                    0
Age                        0
Gender                     0
Sleep Quality              0
Bedtime                    0
Wake-up Time               0
Daily Steps                0
Calories Burned            0
Physical Activity Level    0
Dietary Habits             0
Sleep Disorders            0
Medication Usage           0
Sleep Duration             0
dtype: int64

### 7. Add a column called Age Group that categorizes users into Young (0-30), Middle-aged (31-60), and Senior (60+) based on their age

In [84]:
bins = [0, 30, 60, float('inf')]
labels = ['Young', 'Middle-aged', 'Senior']

df['Age Group'] = pd.cut(df['Age'], bins=bins, labels=labels, right=True, include_lowest=True)
print(df.head(10).to_string(index=False))

 User ID  Age Gender  Sleep Quality             Bedtime        Wake-up Time  Daily Steps  Calories Burned Physical Activity Level Dietary Habits Sleep Disorders Medication Usage  Sleep Duration   Age Group
       1   25      f              8 1900-01-01 23:00:00 1900-01-01 06:30:00         8000             2500                  medium        healthy              no               no             7.5       Young
       2   34      m              7 1900-01-01 00:30:00 1900-01-01 07:00:00         5000             2200                     low      unhealthy             yes              yes             6.5 Middle-aged
       3   29      f              9 1900-01-01 22:45:00 1900-01-01 06:45:00         9000             2700                    high        healthy              no               no             8.0       Young
       4   41      m              5 1900-01-01 01:00:00 1900-01-01 06:30:00         4000             2100                     low      unhealthy             yes               no             5.5 Middle-aged
       5   22      f              8 1900-01-01 23:30:00 1900-01-01 07:00:00        10000             2800                    high         medium              no               no             7.5       Young
       6   37      m              6 1900-01-01 00:15:00 1900-01-01 07:15:00         6000             2300                  medium      unhealthy              no              yes             7.0 Middle-aged
       7   30      f              8 1900-01-01 22:30:00 1900-01-01 06:00:00         8500             2600                    high        healthy              no               no             7.5       Young
       8   45      m              4 1900-01-01 01:30:00 1900-01-01 07:00:00         3000             2000                     low      unhealthy             yes              yes             5.5 Middle-aged
       9   27      f              9 1900-01-01 23:00:00 1900-01-01 07:30:00         9500             2750                  medium        healthy              no               no             8.5       Young
      10   32      m              7 1900-01-01 00:45:00 1900-01-01 07:15:00         6500             2400                  medium         medium              no               no             6.5 Middle-aged

### 8. Identify the users who report taking medication and have a Sleep Disorder. Display their User ID, Age, and Medication Usage

In [85]:
# Filter users with Medication Usage and Sleep Disorders
med_sleep_disorder_users = df[(df['Medication Usage'] == 'yes') & (df['Sleep Disorders'] == 'yes')]

# Display User ID, Age, and Medication Usage
print(med_sleep_disorder_users[['User ID', 'Age', 'Medication Usage']])

    User ID  Age Medication Usage
1         2   34              yes
7         8   45              yes
10       11   50              yes
13       14   48              yes
17       18   39              yes
25       26   44              yes
37       38   50              yes
41       42   44              yes
57       58   45              yes
65       66   43              yes
73       74   50              yes
81       82   42              yes
89       90   47              yes
97       98   46              yes

### 9. Calculate the total Calories Burned by each Age Group (from the column you created in question 7)

In [87]:
# Group by Age Group and calculate total Calories Burned
calories_by_age_group = df.groupby('Age Group')['Calories Burned'].sum()

print(calories_by_age_group)

Age Group
Young           94350
Middle-aged    147750
Senior              0
Name: Calories Burned, dtype: int64

### 10. Sort the dataset by Physical Activity Level in descending order and display the top 5 users by Physical Activity Level, along with their User ID, Daily Steps, and Calories Burned

In [88]:
category_order = ['low', 'medium', 'high']

# Convert the 'Physical Activity Level' column to categorical with the specified order
df['Physical Activity Level'] = pd.Categorical(df['Physical Activity Level'], categories=category_order, ordered=True)

# Now, sort the DataFrame by the 'Physical Activity Level' column
sorted_df = df.sort_values(by='Physical Activity Level', ascending=False)

# for debugging, all supposed to have high phys. act. levels
# print(sorted_df.head(5).to_string(index=False))

print(sorted_df[['User ID', 'Daily Steps', 'Calories Burned']].head(5))

    User ID  Daily Steps  Calories Burned
50       51         9500             2700
28       29         9000             2500
82       83         9500             2700
80       81         8500             2600
44       45         9000             2500